In [ ]:
### JALANKAN CELL INI TERLEBIH DAHULU ###
!pip install sqlalchemy==1.4.46
!pip install pandasql

Collecting sqlalchemy==1.4.46
  Downloading SQLAlchemy-1.4.46-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.7 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy==1.4.46) (3.0.3)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.24
    Uninstalling SQLAlchemy-2.0.24:
      Successfully uninstalled SQLAlchemy-2.0.24
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.46 which is incompatible.
Successfully installed sqlalchemy-1.4.46
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.23.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.5.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (from pandasql) (1.4.46)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pandasql) (2023.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy->pandasql) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26772 sha256=cb9fccea5cd40c384fab85933231d13a0209a42537a0c2aa925e7d0bbd587aac
  Stored in directory: /root/.cache/pip/wheels/e9/bc/3a/8434bdcccf5779e72894a9b24fecbdcaf97940607eaf4bcdf9
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
import pandas as pd
import pandasql

from pandasql import sqldf
sql_run = lambda q: sqldf(q, globals())

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
worldcity = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Extra Class/sql/worldcities.csv', sep = ';', encoding = 'latin-1')
uscity = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Extra Class/sql/uscities.csv', sep = ';', encoding = 'latin-1')
uscity.columns = ['city', 'state_id', 'state_name', 'county_fips', 'county_name',
       'lat', 'lng', 'population', 'density', 'source', 'military',
       'incorporated', 'timezone', 'ranking', 'zips', 'id']

### Tutorial Bagaimana Cara Melakukan Query Menggunakan Pandasql

Contoh: Bagaimana melakukan query untuk mendapatkan kota-kota dari worldcity yang merupakan:
- berada di antara 33 - 40 'latitude'
- berada di antara 100 - 140 'longitude'
- merupakan kota 'primary' pada kolom 'capital'
- memiliki populasi lebih dari 20 juta

In [ ]:
worldcity

,city,lat,lng,country,iso2,iso3,capital,population,id
0,Tokyo,35.6897,139.6922,Japan,JP,JPN,primary,37977000.0,1392685764
1,Jakarta,-6.2146,106.8451,Indonesia,ID,IDN,primary,34540000.0,1360771077
2,Delhi,28.6600,77.2300,India,IN,IND,admin,29617000.0,1356872604
3,Mumbai,18.9667,72.8333,India,IN,IND,admin,23355000.0,1356226629
4,Manila,14.6000,120.9833,Philippines,PH,PHL,primary,23088000.0,1608618140
...,...,...,...,...,...,...,...,...,...
40996,Tukchi,57.3670,139.5000,Russia,RU,RUS,NaN,10.0,1643472801
40997,Numto,63.6667,71.3333,Russia,RU,RUS,NaN,10.0,1643985006
40998,Nord,81.7166,-17.8000,Greenland,GL,GRL,NaN,10.0,1304217709
40999,Timmiarmiut,62.5333,-42.2167,Greenland,GL,GRL,NaN,10.0,1304206491
41000,Nordvik,74.0165,111.5100,Russia,RU,RUS,NaN,0.0,1643587468

In [ ]:
query = """
SELECT DISTINCT city
FROM worldcity
WHERE lat BETWEEN 33 and 40
AND lng BETWEEN 100 and 140
AND capital = 'primary'
AND population > 20000000
"""

sql_run(query)

    city
0  Tokyo
1  Seoul

In [ ]:
uscity

### Question 1 Point : 40

Temukan kota-kota dari worldcity yang memenuhi semua kondisi ini:
- populasi kota tersebut melebih populasi dari kota terbanyak penduduknya di negara Filipina. (Maksudnya: misalnya kota X adalah kota di Filipina yang paling banyak penduduknya. Kita mau daftar kota-kota yang jumlah penduduknya lebih besar dari kota X tersebut), DAN
- ada kota di Amerika Serikat (uscity) dengan nama kota yang sama dengan kota-kota pilihan

Keluarkan hanya nama kota-kota yang memenuhi 2 syarat di atas saja, tidak usah kolom-kolom lain.

##### NOTE: Hilangkan duplicate rows.

Lakukan hanya 1x query saja, jangan melakukan lebih dari 1 query

In [40]:
query = """
SELECT DISTINCT city
FROM worldcity w
WHERE population > (select max(population) FROM worldcity where country = 'Philippines')
AND city = (select city from uscity u where w.city=u.city )

"""


sql_run(query)

    city
0  Delhi

### Question 2 Point : 60

Temukan kota-kota di Amerika Serikat (uscity) yang memenuhi semua kondisi berikut:
- memiliki nama 'city' yang tidak sama dengan 'state_name', dan juga
- memiliki populasi di atas rata-rata populasi kota-kota di 'county_name' Miami-Dade, dan juga
- terdiri dari dua atau lebih kata (contoh: Los Angeles, New York)

Output yang diharapkan hanya kolom 'city' saja, tidak usah kolom yang lain

Lakukan hanya 1x query saja, jangan melakukan lebih dari 1 query

In [41]:
query = """
SELECT DISTINCT city
FROM uscity
WHERE city <> state_name
AND population > (select avg(population) FROM uscity where county_name = 'Miami-Dade')
AND LENGTH(city) - LENGTH(REPLACE(city, ' ', '')) >=1
"""
sql_run(query)

                city
0        Los Angeles
1      San Francisco
2          San Diego
3          Las Vegas
4        San Antonio
..               ...
84        South Lyon
85      Lehigh Acres
86  East Los Angeles
87        St. George
88         Yuba City

[89 rows x 1 columns]